# Generated by Django 5.2.4 on 2025-08-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Tekst koji je korisnik unio.', verbose_name='Korisnikovo Pitanje')),
                ('response', models.TextField(help_text='Tekst koji je AI generirao kao odgovor.', verbose_name='Geminijev Odgovor')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vrijeme Zapisa')),
            ],
            options={
                'verbose_name_plural': 'Gemini Zapisi',
                'ordering': ['-timestamp'],
            },
        ),
    ]
