# Generated by Django 5.2.4 on 2025-08-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminiquery',
            name='raw_response',
            field=models.JSONField(blank=True, null=True, verbose_name='Sirovi JSON Odgovor'),
        ),
        migrations.AddField(
            model_name='geminiquery',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj Tokena'),
        ),
        migrations.AlterField(
            model_name='geminiquery',
            name='question',
            field=models.TextField(verbose_name='Korisnikovo Pitanje'),
        ),
        migrations.AlterField(
            model_name='geminiquery',
            name='response',
            field=models.TextField(verbose_name='Geminijev Odgovor'),
        ),
    ]
