# Generated by Django 5.2.4 on 2025-08-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0002_geminiquery_raw_response_geminiquery_token_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminiquery',
            name='client_request',
            field=models.JSONField(blank=True, help_text='JSON paket koji je poslan Gemini API-ju, uključujući povijest.', null=True, verbose_name='Poslani API Request'),
        ),
    ]
