# Generated by Django 5.2.4 on 2025-08-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0003_geminiquery_client_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminiquery',
            name='existing_content',
            field=models.TextField(blank=True, help_text="Sadržaj fajlova na disku u trenutku klika na 'Primjeni'.", null=True, verbose_name='Zatečeni Sadržaj Fajlova'),
        ),
    ]
