# Generated by Django 5.2.4 on 2025-08-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gemini', '0004_geminiquery_existing_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminiquery',
            name='is_integrated',
            field=models.BooleanField(default=False, verbose_name='Promjene Primijenjene'),
        ),
        migrations.AlterField(
            model_name='geminiquery',
            name='client_request',
            field=models.JSONField(blank=True, null=True, verbose_name='Poslani API Request'),
        ),
        migrations.AlterField(
            model_name='geminiquery',
            name='existing_content',
            field=models.TextField(blank=True, null=True, verbose_name='Zatečeni Sadržaj Fajlova'),
        ),
    ]
